In [1]:
a = [1, 2, 3]
print(a + [4, 5])   # [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np

b = np.array([1, 2, 3])   # array 就是「專門拿來做數值運算的多維資料結構」 ndarray才能做陣列運算
print(b + np.array([4, 5, 6]))   #[5 7 9]

[5 7 9]


In [4]:
import numpy as np

arr1 = np.array([4, 2.5, 6, 3, 5, 9])
print(type(arr1))


<class 'numpy.ndarray'>


In [5]:
arr2 = arr1 * 5
arr2

array([20. , 12.5, 30. , 15. , 25. , 45. ])

In [6]:
arr3 = arr1 / 10
arr3

array([0.4 , 0.25, 0.6 , 0.3 , 0.5 , 0.9 ])